### ISSUE TITLE
Upgrading should keep child sites

### ISSUE THREAD

**Issue by cdw9** [collective/collective.lineage#29]
I have not tested this, but the changelog for 2.0 states, "Please make a list of all your subsites before, as you have to re-enable them manually. There is no upgrade step for this yet."

It's possible this already works, since I copied a lot of code from Lineage to EasySlidshow, and the subtyped folders stay as Slideshow Folders after upgrading.

**Comment by claytron** [comment]
@calvinhp was this done as part of the 2.0 upgrade already?

**Comment by thet** [comment]
AFAIK i added this note. but that was obsolete since ever, because the interfaces were not changed with the 2.0 release. subsites should work as expected also after upgrading from 1.x to 2.x.
