### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by thet** [collective/collective.lineage#39]
@calvinhp @claytron can we have a new release of collective lineage? besides some general improvements, it also fixes this bug: https://github.com/collective/collective.lineage/issues/38#issuecomment-178500164

or can i haz pypi rights for collective.lineage? username: thet

**Comment by jensens** [comment]
indeed, this would be great!

**Comment by calvinhp** [comment]
Actually, we are in a good spot to do one, Shane just sent in a [PR]( #41 ) that fixes a major upgrade issue from older versions. Let me get that reviewed and we can do a release.

**Comment by jensens** [comment]
:+1:

**Comment by thet** [comment]
ping

**Comment by tisto** [comment]
@calvinhp any news on this issue? Would be great to have a new release!

**Comment by thet** [comment]
@calvinhp what about opening collective.lineage to a broader release team? I'd be happt to volunteer for such a task. My pypi username is:
thet

**Comment by jensens** [comment]
@calvinhp this is overdue in my opinion? lost interest in this package? my pypi user name is jensens - happy to help here!

**Comment by calvinhp** [comment]
I'm going to pull down master and review this week.  I'll get a 2.1 release out by end-of-week if it kills me.

**Comment by calvinhp** [comment]
2.1 has just been released, sorry for the delay on that one
