### ISSUE TITLE
Unable to add new subsitefolder/subsitepage (cannot see option to select) in Plone 5.0.6

### ISSUE THREAD

**Issue by richardtc** [collective/collective.lineage#48]
I've installed Lineage 2.1 in Plone 5.0.6 and cannot see the subsitefolder or subsitepage items under the Add new admin column in Plone.

I've disabled the SunRain theme and activated the Barcelonata but still cannot see these items. I was able to activate a subsite from a folder, but now cannot add a subsitepage?

Any suggestions would be welcome.

Plone 5.0.6 (5016)
CMF 2.2.10
Zope 2.13.24
Python 2.7.12 (default, Sep 2 2016, 21:18:45) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
PIL 3.3.0 (Pillow)

Lineage	2.1	2.1
Lineage Index	0.5	0.5
Lineage: Child Site Local Registry	1.3.3	1.3.3
Lineage: Theme Selection Addon for Child Sites	2.0	2.0

**Comment by richardtc** [comment]
Please see above comment. Thanks.

**Comment by thet** [comment]
In collective.lineage 2.x, you can make any folderish content a subsite by choosing "Enable subsite" from the "Actions" menu in the toolbar.
After you created a subsite like explained, you can add any content to it. You can also create subsites within subsites.

If this doesn't help you, rephrase your question and reopen.

**Comment by richardtc** [comment]
I can do this: 'In collective.lineage 2.x, you can make any folderish content a subsite by choosing "Enable subsite" from the "Actions" menu in the toolbar.'

I can also add a page and other items to the enabled subsitefolder. However, on another site (with the same specs) I can see subsitefolder and subsitepage content items under the "Add new" menu, but on my current site these are not visible?  Anyway, I guess they are not needed.
.

**Comment by thet** [comment]
That might be a custom integration of lineage. We're using it in one project like that too - creating an special "subsite" object with specific limitations on what can be added and so forth automatically enables the subsite. but that's integration specific.
