### ISSUE TITLE
2.3 release with Python 3 support?

### ISSUE THREAD

**Issue by zopyx** [collective/collective.lineage#55]
Would it be possible to cut a Python 3 compatible 2.3 release?

**Comment by tkimnguyen** [comment]
I'm getting errors with 2.3.dev0 on Python 3.7: #57

**Comment by tkimnguyen** [comment]
Given the errors in #57 I think we should try to track down the bug before making a release, because it has to be in lineage.

**Comment by tkimnguyen** [comment]
@zopyx the fix as described in https://github.com/collective/collective.lineage/issues/57#issuecomment-584859266 is to pin plone.dexterity to 2.9.3 or later (2.9.5 is current). How can we require >= 2.9.3 only if using Python 3?

**Comment by petri** [comment]
https://www.python.org/dev/peps/pep-0508/#environment-markers to the rescue?

**Comment by tkimnguyen** [comment]
thx @petri 😄  https://pypi.org/project/collective.lineage/2.3/ released @zopyx
