### ISSUE TITLE
There is no 2.3 tag in this repo even though there is a 2.3 release on Pypi

### ISSUE THREAD

**Issue by gotcha** [collective/collective.lineage#63]
@tkimnguyen Would you happen to know who did that 2.3 release ?

**Comment by thet** [comment]
I added the tag for 2.3. The release was with after this commit. https://github.com/collective/collective.lineage/commit/05d6516e158ddcee9e5a5fdaf5dc4108e4cb3f6b

Let's just use zest.releaser, then this isn't an issue anymore.
